In [31]:
import cv2
import numpy as np
from skimage.feature import peak_local_max

In [32]:
imagen = cv2.imread("img/bailarina.png", cv2.IMREAD_GRAYSCALE)

_, imagen_bin = cv2.threshold(
    imagen,
    0,
    255,
    cv2.THRESH_BINARY | cv2.THRESH_OTSU
)

cv2.imshow("Imagen Binaria", imagen_bin)
cv2.waitKey(0)

-1

In [33]:
kernel = np.ones((3,3), np.uint8)

imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_GRADIENT, kernel)
imagen_bin = cv2.dilate(imagen_bin, kernel, iterations=3)

cv2.imshow("Preprocesamiento", imagen_bin)
cv2.waitKey(0)

-1

In [34]:
matriz_distancias = cv2.distanceTransform(
    imagen_bin,
    cv2.DIST_L1,
    3
)

print(matriz_distancias)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
skeleton = np.zeros(imagen_bin.shape, dtype=np.uint8)

coords = peak_local_max(matriz_distancias, min_distance=1)

for coord in coords:
    skeleton[coord[0], coord[1]] = 255

In [36]:
cv2.imshow("Esqueleto", skeleton)
cv2.waitKey(0)
cv2.destroyAllWindows()