In [1]:
import cv2
import numpy as np

In [2]:
imagen = cv2.imread("img/mano.jpeg", cv2.IMREAD_GRAYSCALE)
_,imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

cv2.imshow("Imagen", imagen_bin)
cv2.waitKey(0)

-1

In [3]:
# Matriz de prueba
imagen_bin = np.matrix([
    [1,1,1],
    [1,0,1],
    [1,1,1]
]).astype(np.uint8)

imagen_bin

matrix([[1, 1, 1],
        [1, 0, 1],
        [1, 1, 1]], dtype=uint8)

In [4]:
h, w = imagen_bin.shape
matriz_distancias = (h + w) * imagen_bin.astype(np.uint16)
matriz_distancias

matrix([[6, 6, 6],
        [6, 0, 6],
        [6, 6, 6]])

In [5]:
# Primera pasada
for y in range(h):
    for x in range(w):
        norte = y - 1
        oeste = x - 1
        if norte < h and norte >= 0:
            pixel_norte = matriz_distancias[norte, x]
        else:
            pixel_norte = h + w
        if oeste < w and oeste >= 0:
            pixel_oeste = matriz_distancias[y, oeste]
        else:
            pixel_oeste = h + w
    
        matriz_distancias[y,x] = min(matriz_distancias[y,x], pixel_norte + 1, pixel_oeste + 1)

print(matriz_distancias)

[[6 6 6]
 [6 0 1]
 [6 1 2]]


In [6]:
# Segunda Pasada
for y in range(h-1, -1, -1):
    for x in range(w-1, -1, -1):
        sur = y + 1
        este = x + 1
        if sur < h and sur >= 0:
            pixel_sur = matriz_distancias[sur, x]
        else:
            pixel_sur = h + w
        if este < w and este >= 0:
            pixel_este = matriz_distancias[y, este]
        else:
            pixel_este = h + w
        
        matriz_distancias[y,x] = min(matriz_distancias[y,x], pixel_sur + 1, pixel_este + 1)

print(matriz_distancias)

[[2 1 2]
 [1 0 1]
 [2 1 2]]


In [7]:
matriz_distancias

matrix([[2, 1, 2],
        [1, 0, 1],
        [2, 1, 2]])

In [8]:
matriz_distancias_2 = cv2.distanceTransform(imagen_bin, cv2.DIST_L1, 3)

In [9]:
%pip install scikit-image

Note: you may need to restart the kernel to use updated packages.


In [10]:
from skimage.feature import peak_local_max

skeleton = np.zeros(imagen_bin.shape, dtype=np.uint8)
coords = peak_local_max(matriz_distancias, min_distance=1)
for coord in coords:
    skeleton[coord[0], coord[1]] = 255
cv2.imshow("Distancias", skeleton)
cv2.waitKey(0)

IndexError: index 0 is out of bounds for axis 0 with size 0